matrix:
  - name: HTML Files
    sources:
      - '**/*.html'
    spelling:
      language: en_US
      dictionary: en_US
      ignore-comments: false
      ignore-strings: true
      filters:
        - html
      word-lists:
        - .spelling-words.txt

