name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.36.0
        with:
          task_name: default
